name = "tuziyo"
pages_build_output_dir = "./build/client"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
PUBLIC_APP_ORIGIN = "https://tuziyo.com"
BASE_URL = "/blog/"
BUN_VERSION = "latest"
[[d1_databases]]
binding = "DB"
database_name = "tuziyo-db"
database_id = "87c3889f-0a77-4252-8cd5-f59dbc523d0f"

[[r2_buckets]]
binding = "R2"
bucket_name = "tuziyo-images"
preview_bucket_name = "tuziyo-images"
