name = "tuziyo-worker"
main = "src/index.ts"
compatibility_date = "2026-07-06"

[triggers]
crons = ["0 0 * * *", "10 0 * * *", "* * * * *"]

[vars]
FRONTEND_URL="https://tuziyo.com"
MEDIA_BASE_URL = "https://api.tuziyo.com"
R2_ACCOUNT_ID = "2b00eb739bd84104c948e47541a47b2a"
R2_BUCKET_NAME = "tuziyo"  # R2 存储桶名称
EVOLINK_CALLBACK_URL = "https://api.tuziyo.com/api/evolink/callback"

[ai]
binding = "AI"
remote = true

[images]
binding = "IMAGES"
remote = true

[cache]
enabled = true

[[r2_buckets]]
binding = "R2"
bucket_name = "tuziyo"
preview_bucket_name="tuziyo"

[[d1_databases]]
binding = "DB"
database_name = "tuziyo-db"
database_id = "87c3889f-0a77-4252-8cd5-f59dbc523d0f"


[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false
