name = "tuziyo-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
R2_PUBLIC_BASE_URL = "https://s3.tuziyo.com"

[ai]
binding = "AI"
remote = true

[[r2_buckets]]
binding = "R2"
bucket_name = "tuziyo"
preview_bucket_name="tuziyo"

[[d1_databases]]
binding = "DB"
database_name = "tuziyo-db"
database_id = "87c3889f-0a77-4252-8cd5-f59dbc523d0f"
